-- MySQL Script generated by MySQL Workbench
-- Fri Apr 19 20:29:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema redeSocial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema redeSocial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `redeSocial` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `redeSocial` ;

-- -----------------------------------------------------
-- Table `redeSocial`.`TbUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `redeSocial`.`TbUsuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL,
  `documento` VARCHAR(50) NULL,
  `dataNascimento` DATE NULL,
  `dataCadastro` VARCHAR(45) NULL,
  `email` VARCHAR(60) NULL,
  `senha` VARCHAR(50) NULL,
  `nivelAcesso`enum('PACIENTE','MEDICO','ADMINISTRADOR') NULL,
  `ddd` VARCHAR(5) NULL,
  `telefone` VARCHAR(15) NULL,
  `sexo` VARCHAR(10) NULL,
  `imagem` VARCHAR(150) NULL,
  `idAmigo1` INT NULL,
  `idAmigo2` INT NULL,
  `idAmigo3` INT NULL,
  `idAmigo4` INT NULL,
  `idAmigo5` INT NULL,
  `idAmigo6` INT NULL,
  `titulo1` VARCHAR(50) NULL,
  `descricao1` VARCHAR(45) NULL,
  `titulo2` VARCHAR(50) NULL,
  `descricao2` VARCHAR(45) NULL,
  `titulo3` VARCHAR(50) NULL,
  `descricao3` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `redeSocial`.`tbComentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `redeSocial`.`tbComentario` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(50) NULL,
  `emailUsuario` VARCHAR(60) NULL,
  `dataHora` DATETIME NULL,
  `comentario` TEXT NULL,
  `resposta1` TEXT NULL,
  `resposta2` TEXT NULL,
  `resposta3` TEXT NULL,
  `idDestinatario` INT NULL,
  `TbUsuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `fk_tbComentario_TbUsuario_idx` (`TbUsuario_idUsuario` ASC),
  CONSTRAINT `fk_tbComentario_TbUsuario0`
    FOREIGN KEY (`TbUsuario_idUsuario`)
    REFERENCES `redeSocial`.`TbUsuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO tbUsuario(nome, documento, dataNascimento, dataCadastro, email, senha, nivelAcesso, ddd, telefone, sexo, imagem, idAmigo1, idAmigo2, totulo1, titulo2, descricao1, descricao2)
VALUES('Alessandro dos Santos', '123456','1990-03-28',curdate(),'alessandro@rede.com.br','123456','ADMINISTRADOR','013','33424849','M', '8aca6235-81fb-47c8-9f24-23a5a886bd1b.jpg', 2, 3, 'Descricao de testes 1', 'Deixe o Jaleko te Ajudar nos 6 Anos Mais Importantes da Sua Vida! Muito mais que medicina. Estude em pouco tempo. Preço que Cabe no Bolso. Estude Onde Quiser. Mais de 100h de Aulas. Aprenda e reforce. +6mil Questões Comentadas. Cursos: Anatomia, Fisiologia, Bioquímica, Cirur', 'Descricao de testes 2', 'Deixe o Jaleko te Ajudar nos 6 Anos Mais Importantes da Sua Vida! Muito mais que medicina. Estude em pouco tempo. Preço que Cabe no Bolso. Estude Onde Quiser. Mais de 100h de Aulas. Aprenda e reforce. +6mil Questões Comentadas. Cursos: Anatomia, Fisiologia, Bioquímica, Cirur'),
('Lucas Santos','123456','1990-03-28',curdate(),'lucas@rede.com.br','123456','ADMINISTRADOR','013','33424849','M', '8aca6235-81fb-47c8-9f24-23a5a886bd1b.jpg', 1, 3, 'Descricao de testes 1', 'Deixe o Jaleko te Ajudar nos 6 Anos Mais Importantes da Sua Vida! Muito mais que medicina. Estude em pouco tempo. Preço que Cabe no Bolso. Estude Onde Quiser. Mais de 100h de Aulas. Aprenda e reforce. +6mil Questões Comentadas. Cursos: Anatomia, Fisiologia, Bioquímica, Cirur', 'Descricao de testes 2', 'Deixe o Jaleko te Ajudar nos 6 Anos Mais Importantes da Sua Vida! Muito mais que medicina. Estude em pouco tempo. Preço que Cabe no Bolso. Estude Onde Quiser. Mais de 100h de Aulas. Aprenda e reforce. +6mil Questões Comentadas. Cursos: Anatomia, Fisiologia, Bioquímica, Cirur'),
('Thiago', '123456','1990-03-28',curdate(),'thiago@rede.com.br','123456','ADMINISTRADOR','013','33424849','M', '8aca6235-81fb-47c8-9f24-23a5a886bd1b.jpg', 1, 2, 'Descricao de testes 1', 'Deixe o Jaleko te Ajudar nos 6 Anos Mais Importantes da Sua Vida! Muito mais que medicina. Estude em pouco tempo. Preço que Cabe no Bolso. Estude Onde Quiser. Mais de 100h de Aulas. Aprenda e reforce. +6mil Questões Comentadas. Cursos: Anatomia, Fisiologia, Bioquímica, Cirur', 'Descricao de testes 2', 'Deixe o Jaleko te Ajudar nos 6 Anos Mais Importantes da Sua Vida! Muito mais que medicina. Estude em pouco tempo. Preço que Cabe no Bolso. Estude Onde Quiser. Mais de 100h de Aulas. Aprenda e reforce. +6mil Questões Comentadas. Cursos: Anatomia, Fisiologia, Bioquímica, Cirur')

INSERT INTO tbComentario(nomeUsuario, emailUsuario, comentario, resposta1, resposta2, resposta3, TbUsuario_idUsuario, dataHora)
VALUES('Alessandro dos Santo','alessandro@rede.com.br', 'Comentario Teste 1', 'Resposta teste 2', 'Resposta teste2', 'Resposta teste 3', 1, curdate()),
('Alessandro dos Santo','alessandro@rede.com.br', 'Comentario Teste 1', 'Resposta teste 2', 'Resposta teste2', 'Resposta teste 3', 1, curdate()),
('Alessandro dos Santo','alessandro@rede.com.br', 'Comentario Teste 1', 'Resposta teste 2', 'Resposta teste2', 'Resposta teste 3', 1,curdate())